apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Service
metadata:
  name: epiphany-examples-web-svc
  namespace: demo
  labels:
    version: 1.0.0
spec:
  selector:
    app: epiphany-examples-web
    version: 0.2.1
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30090
  - name: https-port
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 31143
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epiphany-examples-web
  namespace: demo
spec:
  selector:
    matchLabels:
      app: epiphany-examples-web
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: epiphany-examples-web
        version: 0.2.1
    spec:
      containers:
      - name: epiphany-examples-web
        image: epiphanyplatform/examples-web:0.2.1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 15
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        # Kubernetes specific - no need to change
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        # ---
